### ISSUE TITLE
mechanical crafting jei will broken when this mod is installed

### ISSUE THREAD

**Issue by magcicada** [Dremoline/PortableTanks#4]
Minecraft 1.16.5
portabletanks-1.1.2-mc1.16

The mechanical crafting jei page of Create mod will broken when this mod is installed.

**Comment by SuperMartijn642** [comment]
There doesn't appear to be a page for mechanical crafting as the mechanical crafter just uses normal recipes. What page are you referring to?

The recipe for the mechanical crafter appears as normal.
![image](https://user-images.githubusercontent.com/12382965/144645467-3d89d369-89cf-4185-b068-b09e5ec370a5.png)

All the tabs in JEI also appear as normal, however there's none for mechanical crafting.
![image](https://user-images.githubusercontent.com/12382965/144645629-6b317aeb-bb47-422b-a2aa-9d22ae813075.png)
![image](https://user-images.githubusercontent.com/12382965/144645660-60544370-5527-4d40-bfec-4aa2d20e3023.png)
![image](https://user-images.githubusercontent.com/12382965/144645684-1d7d7e35-6cf7-4bbf-af1e-3433377e33a9.png)

**Comment by SuperMartijn642** [comment]
Nevermind, I get what you mean now. Your point is that the tab doesn't appear.
I fixed it with ffda59093d3e40b99ba201749c4b807d46a4f54f.

@Dremoline will likely include in the next update.

**Comment by SuperMartijn642** [comment]
It is fixed now in Portable Tanks 1.1.3.

Thank you for reporting the issue!
