### ISSUE TITLE
[Crash] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [Dremoline/PortableTanks#6]
Minecraft 1.19
Forge 41.0.94+
supermartijn642configlib-1.1.6b-forge-mc1.19
supermartijn642corelib-1.0.19-forge-mc1.19
portabletanks-1.1.5-forge-mc1.19

java.lang.NoClassDefFoundError: net/minecraftforge/forge/event/lifecycle/GatherDataEvent

[crashlog](https://github.com/Dremoline/PortableTanks/files/9126996/crash-2022-07-17_13.30.59-fml.txt)

**Comment by SuperMartijn642** [comment]
I updated everything to Forge 41.0.94 now in e6524afb550f269b0706006cb7da94faffdada5c. Up to @Dremoline to release an update.

**Comment by SuperMartijn642** [comment]
Fixed now in Portable Tanks 1.1.5a for 1.19.
Thank you for reporting the issue!

**Comment by Baggytrousers27** [comment]
¦D
